name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag digilbum-back:${{ github.run_number }}

        # Envoi de l'image vers la VM via SSH
      - name: Save Docker image to a file
        run: docker save digilbum-back:${{ github.run_number }} | gzip > digilbum-back.tar.gz

      - name: Transfer Docker image to VM
        uses: appleboy/scp-action@master
        with:
          source: "digilbum-back.tar.gz"
          target: "~/app/back/"
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}

      # Chargement et lancement de l'image sur la VM
      - name: Deploy Docker image on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker load < ~/app/back/digilbum-back.tar.gz
            docker run -d -p 8080:8080  -v ~/pictures:/home/digilbum/pictures digilbum-back:${{ github.run_number }}
